name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo helloo world 

      - name: Deploying using ssh
        uses: tavethiyaparul/Todo/ssh-action@main
        with:
          host:  ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/public_html/demo_project/Todo/
            sudo rm -rf node_modules
            sudo git pull
            sudo yarn install
            pm2 list
            pm2 restart 1