name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    retries: 3 # You can adjust the number of retries
    continue-on-error: true
    steps:
      - name: Print Hello World
        run: echo helloo world asdads

      - name: Deploying using ssh
        uses: tavethiyaparul/Todo/ssh-action@main
        with:
          host: 167.86.109.223
          username: root
          password: 77NHg9e5YT9Jpmsc3
          port: 22
          script: |
            cd /var/www/public_html/demo_project/Todo/
            sudo rm -rf node_modules
            sudo git pull
            sudo yarn install
            pm2 list
            pm2 restart 1